# Generated by Django 4.0 on 2022-01-31 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum', '0001_initial'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('cropName', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('genericProblems', models.CharField(max_length=500)),
                ('weatherProblems', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('area', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.area')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='users.customuser')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
