# Generated by Django 4.0.1 on 2022-01-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvestreport',
            name='genericProblems',
            field=models.CharField(default='abc', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='weatherProblems',
            field=models.CharField(default='cde', max_length=500),
            preserve_default=False,
        ),
    ]
