# Generated by Django 4.0 on 2022-01-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('report', '0002_harvestreport_genericproblems_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestreport',
            name='cropCategory',
        ),
        migrations.AddField(
            model_name='harvestreport',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='forum.category'),
        ),
        migrations.DeleteModel(
            name='CropCategory',
        ),
    ]
