# Generated by Django 4.0 on 2022-01-31 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipmessage',
            name='reference_tip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.tiprequest'),
        ),
        migrations.AddField(
            model_name='hrmessage',
            name='reference_hr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.helprequest'),
        ),
    ]
