# Generated by Django 4.0 on 2022-01-29 14:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_helprequest_status'),
        ('chat', '0002_message_receiver_alter_message_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(max_length=250)),
                ('isFromSender', models.BooleanField()),
                ('reference_hr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.helprequest')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
