# Generated by Django 4.0 on 2022-01-29 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_helprequest_status'),
        ('chat', '0003_hrmessage_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('body', models.CharField(max_length=250)),
                ('isFromFarmer', models.BooleanField()),
                ('reference_tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.tiprequest')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
