# Generated by Django 4.0 on 2022-01-31 18:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('proposed_title', models.CharField(max_length=250)),
                ('proposed_tip', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Policymaker Review'), ('farmer', 'Farmer Turn'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='not_accepted', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiprequest_author', to='users.customuser')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tiprequest_receiver', to='users.customuser')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('not_accepted', 'Not-accepted'), ('closed', 'Closed'), ('declined', 'Declined')], default='not_accepted', max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hrrequest_author', to='users.customuser')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hrrequest_receiver', to='users.customuser')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
