# Generated by Django 4.0 on 2022-01-29 00:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helprequest',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='helprequest',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hrrequest_author', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='hrrequest_receiver', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='helprequest',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='status',
            field=models.CharField(choices=[('accepted', 'Draft'), ('not_accepted', 'Not-accepted'), ('closed', 'Closed')], default='not_accepted', max_length=20),
        ),
    ]
