# Generated by Django 4.0 on 2022-01-29 01:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_helprequest_options_helprequest_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helprequest',
            name='slug',
        ),
        migrations.AlterField(
            model_name='helprequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
