# Generated by Django 4.0 on 2022-01-29 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '__first__'),
        ('request', '0004_alter_helprequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiprequest',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='published',
        ),
        migrations.AddField(
            model_name='tiprequest',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tiprequest_author', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiprequest',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='tiprequest_receiver', to='users.customuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tiprequest',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in-progress', 'In Progress'), ('refused', 'Refused'), ('declined', 'Declined'), ('accepted', 'Accepted')], default='not_accepted', max_length=20),
        ),
    ]
