# Generated by Django 4.0 on 2022-01-29 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_alter_tiprequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiprequest',
            name='published',
        ),
        migrations.RemoveField(
            model_name='tiprequest',
            name='slug',
        ),
    ]
