# Generated by Django 4.0 on 2022-01-26 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.area'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='users.area'),
        ),
        migrations.AlterField(
            model_name='tip',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tip',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('text_body', models.TextField()),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_Answers', to='users.customuser')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.question')),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
